### ISSUE TITLE
Installation failure of plugin include-csv

### ISSUE THREAD

**Issue by PeterBowman** [roboticslab-uc3m/docker-gitbook#1]
Last night docker&gitbook CI builds of teo-developer-manual [failed](https://github.com/roboticslab-uc3m/teo-developer-manual/runs/4269867395?check_suite_focus=true#step:4:40) with:

```
info: installing 6 plugins using npm@3.9.2 
info:  
info: installing plugin "include-csv" 
info: install plugin "include-csv" (*) from NPM with version 1.0.1 
/root/.gitbook/versions/3.2.3/node_modules/npm/node_modules/aproba/index.js:25
    if (args[ii] == null) throw missingRequiredArg(ii)
                          ^

Error: Missing required argument #1
    at andLogAndFinish (/root/.gitbook/versions/3.2.3/node_modules/npm/lib/fetch-package-metadata.js:31:3)
    at fetchPackageMetadata (/root/.gitbook/versions/3.2.3/node_modules/npm/lib/fetch-package-metadata.js:51:22)
    at resolveWithNewModule (/root/.gitbook/versions/3.2.3/node_modules/npm/lib/install/deps.js:490:12)
    at /root/.gitbook/versions/3.2.3/node_modules/npm/lib/install/deps.js:491:7
    at /root/.gitbook/versions/3.2.3/node_modules/npm/node_modules/iferr/index.js:13:50
    at /root/.gitbook/versions/3.2.3/node_modules/npm/lib/fetch-package-metadata.js:37:12
    at addRequestedAndFinish (/root/.gitbook/versions/3.2.3/node_modules/npm/lib/fetch-package-metadata.js:67:5)
    at returnAndAddMetadata (/root/.gitbook/versions/3.2.3/node_modules/npm/lib/fetch-package-metadata.js:121:7)
    at pickVersionFromRegistryDocument (/root/.gitbook/versions/3.2.3/node_modules/npm/lib/fetch-package-metadata.js:138:20)
    at /root/.gitbook/versions/3.2.3/node_modules/npm/node_modules/iferr/index.js:13:50
Error: Process completed with exit code 1.
```

Eveything was fine just [one week earlier](https://github.com/roboticslab-uc3m/teo-developer-manual/actions/runs/1452917172). Another gitbook-enabled repo succeeded at the same time, but that one does not pull&install include-csv (see [book.json](https://github.com/roboticslab-uc3m/teo-developer-manual/blob/247d89d05e31e85f01f9c76fe2eec34dc3a216a4/book.json#L5)). Pre-installing plugins is probably not the way to go, see https://github.com/roboticslab-uc3m/teo-developer-manual/issues/69#issuecomment-839258111.

I tried to pull [node:current-alpine](https://hub.docker.com/_/node) at node v17.1.0, npm 8.1.4 (previously using node v10.24, npm 6.14.12). The image does not even build correctly, it fails at:

```
Installing GitBook 3.2.3
/usr/local/lib/node_modules/gitbook-cli/node_modules/npm/node_modules/graceful-fs/polyfills.js:287
      if (cb) cb.apply(this, arguments)
                 ^

TypeError: cb.apply is not a function
    at /usr/local/lib/node_modules/gitbook-cli/node_modules/npm/node_modules/graceful-fs/polyfills.js:287:18
    at FSReqCallback.oncomplete (fs.js:169:5)
```

A similar issue regarding the missing required argument was reported [in this SO question](https://stackoverflow.com/q/68499613/10404307), no solutions provided. See also [this one](https://stackoverflow.com/q/63214997/10404307) concerning the `cb.apply` thing. See also https://github.com/npm/cli/issues/681.

**Comment by PeterBowman** [comment]
Idea: I noticed some direct and transitive dependencies of [include-csv](https://www.npmjs.com/package/gitbook-plugin-include-csv) got upgraded in the past week. [Logs](https://github.com/roboticslab-uc3m/teo-developer-manual/runs/4189310063?check_suite_focus=true#step:4:40) of latest successful build:

```
info: install plugin "include-csv" (*) from NPM with version 1.0.1 
/gitbook
`-- gitbook-plugin-include-csv@1.0.1 
  +-- csv-parse@4.16.3 
  +-- iconv-lite@0.6.3 
  | `-- safer-buffer@2.1.2 
  +-- path@0.12.7 
  | +-- process@0.11.10 
  | `-- util@0.10.4 
  |   `-- inherits@2.0.3 
  `-- url@0.11.0 
    +-- punycode@1.3.2 
    `-- querystring@0.2.0 

info: >> plugin "include-csv" installed with success 
```

E.g. [csv-parse](https://www.npmjs.com/package/csv-parse) is now at v5.0.3.

**Comment by jgvictores** [comment]
In the light of https://github.com/roboticslab-uc3m/docker-gitbook/issues/1#issuecomment-974644463 and [failed experiments](https://github.com/roboticslab-uc3m/teo-developer-manual/issues/69#issuecomment-1703793731), forking and forcing specific versions through `package.json` seems like the way to go (btw, I do not remember what the `scripts` plugin was for, so no idea if it could do anything related).

Issue paused on my side for now, not really urgent.

**Comment by PeterBowman** [comment]
We are now migrating to MkDocs, see https://github.com/roboticslab-uc3m/questions-and-answers/issues/99. This Docker image can still be useful as long as the include-csv plugin is not requested in book.json.
